create database CODEBEGUN_TEST_DB;

use CODEBEGUN_TEST_DB;

Create table STUDENT(
STUDENTID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
MOBILENUMBER BIGINT NOT NULL,
EMAILID VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
GENDER BIT NOT NULL);



SELECT * FROM STUDENT;

insert INTO STUDENT(FIRSTNAME,LASTNAME,MOBILENUMBER,EMAILID,GENDER)
VALUES('SAIKUMAR','PORIDA',8688510810,'PORIDASAIKUMAR',1);

insert INTO STUDENT(FIRSTNAME,LASTNAME,MOBILENUMBER,EMAILID,GENDER)
VALUES('SARATH','KING',8688510811,'KINGSARATH',1);

insert INTO STUDENT(FIRSTNAME,LASTNAME,MOBILENUMBER,EMAILID,GENDER)
VALUES('SIVA','QUEEN',8688510812,'QUEENSIVA',1);

insert INTO STUDENT(FIRSTNAME,LASTNAME,MOBILENUMBER,EMAILID,GENDER)
VALUES('SAI','PORI',8688510813,'PORISAI',1);




use CODEBEGUN_TEST_DB;

CREATE TABLE ADDRESS (
ADDRESSID BIGINT AUTO_INCREMENT PRIMARY KEY,
ADDRESS1 varchar(50) NOT NULL,
ADDRESS2 varchar(50) NOT NULL,
TOWN varchar(50) NOT NULL,
CITY varchar(50) NOT NULL,
DISTICT varchar(50) NOT NULL,
STATE varchar(50) NOT NULL,
COUNTRY varchar(50) NOT NULL,
PINCODE bigint(100) NOT NULL
);
 INSERT INTO ADDRESS(ADDRESS1,ADDRESS2,TOWN,CITY,DISTICT,STATE,COUNTRY,PINCODE)
 VALUES ('10-36','GANESHNAGAR','KOTHAKOTA','KOTHAKOTA','WANAPARTHY','Telengana','India',509381);
 
 INSERT INTO ADDRESS(ADDRESS1,ADDRESS2,TOWN,CITY,DISTICT,STATE,COUNTRY,PINCODE)
 VALUES ('10-37','SHEENAGAR','KOTHAKOTA','KOTHAKOTA','ANAPARTHY','Telengana','India',509382);
 
 
 INSERT INTO ADDRESS(ADDRESS1,ADDRESS2,TOWN,CITY,DISTICT,STATE,COUNTRY,PINCODE)
 VALUES ('10-37-3','SHEENAGARCOLONY','PATHAKOTA','PATHAKOTA','ANAPARTHY','Telengana','India',509383);
 
 
 INSERT INTO ADDRESS(ADDRESS1,ADDRESS2,TOWN,CITY,DISTICT,STATE,COUNTRY,PINCODE)
 VALUES ('10-38-3','SHNAGARSTREET','KARIMNAGR','KOTHAKOTA','ANAPARTHY','Telengana','India',509384);
 

 
select * FROM ADDRESS;



CREATE TABLE Register
(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FirstName varchar(50) not null,
LastName varchar(50) not null,
Email varchar(50)  not null,
MobileNumber varchar(50) not null
);

SELECT * FROM Register;

drop table Register;